steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - europe-west2-docker.pkg.dev/trillians-demo-site/trillians/trillians-demo-site:$SHORT_SHA
      - .

  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - europe-west2-docker.pkg.dev/trillians-demo-site/trillians/trillians-demo-site:$SHORT_SHA

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - deploy
      - trillians-demo-site
      - --image
      - europe-west2-docker.pkg.dev/trillians-demo-site/trillians/trillians-demo-site:$SHORT_SHA
      - --region
      - europe-west2
      - --project
      - trillians-demo-site
      - --platform
      - managed
      - --allow-unauthenticated

images:
  - europe-west2-docker.pkg.dev/trillians-demo-site/trillians/trillians-demo-site:$SHORT_SHA

options:
  logging: CLOUD_LOGGING_ONLY
